export interface ReportsProps {
  BackgroundColor: string;
  Trans_Id: string;
  Bkg_Id: string;
  Bkg_Commit: string;
  Pay_Status: string;
  Appl_Name: string;
  Cinema_Name: string;
  Screen_Name: string;
  Event_Name: string;
  Trans_Date: string;
  Show_Date: string;
  Show_Date_Disp: string;
  Ticket_Qty: string;
  Ticketwise_Qty: string;
  Seat_Info: string;
  Ticket_Amt: string;
  Item_Desc: string;
  ItemWise_Amt: string;
  ItemWise_Qty: string;
  Inv_Qty: string;
  Inv_Amt: string;
  Additional_Desc: string;
  Add_strAmt: string;
  Add_Charges: string;
  Cinema_DiscAmt: string;
  Cinema_OfferCode: string;
  ETicket_Status: string;
  SocialDistancing_count: string;
}

export const report = [
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3736910789",
    Bkg_Id: "BGRM013QY0PB59",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45105.44343",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 4-14, 4-15",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3737481102",
    Bkg_Id: "BGRM16G4M17R3J",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45105.8208",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 4-19, 4-20",
    Ticket_Amt: "1000",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "2",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3738141405",
    Bkg_Id: "BGRM00Q47NGT0Q",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Iphone App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45106.43398",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "3",
    Ticketwise_Qty: "3",
    Seat_Info: "Row 1 to 18: 4-16, 4-17, 4-18",
    Ticket_Amt: "1500",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3738527368",
    Bkg_Id: "BGRM00RA98WJY2",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45106.59327",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "4",
    Ticketwise_Qty: "4",
    Seat_Info: "Row 1 to 18: 5-13, 5-14, 5-15, 5-16",
    Ticket_Amt: "2000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3738748238",
    Bkg_Id: "BGRM0S00113AM8",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45106.69226",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "3",
    Ticketwise_Qty: "3",
    Seat_Info: "Row 1 to 18: 4-10, 4-11, 4-12",
    Ticket_Amt: "1500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "3",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3739776108",
    Bkg_Id: "BGRM00ATQ6QKFW",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BookMyShow Website",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45107.46883",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "4",
    Ticketwise_Qty: "4",
    Seat_Info: "Row 1 to 18: 5-17, 5-18, 5-19, 5-20",
    Ticket_Amt: "2000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3741018357",
    Bkg_Id: "BGRM00NU5RJDPU",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BookMyShow Website",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45108.31204",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 5-11, 5-12",
    Ticket_Amt: "1000",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "2",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3741489755",
    Bkg_Id: "BGRM0QYR310T21",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Iphone App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45108.5981",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "3",
    Ticketwise_Qty: "3",
    Seat_Info: "Row 1 to 18: 4-21, 4-22, 5-21",
    Ticket_Amt: "1500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "3",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3743689752",
    Bkg_Id: "BGRM00D6QQDRNA",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45109.8465",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 4-8, 4-9",
    Ticket_Amt: "1000",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "2",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3743824476",
    Bkg_Id: "BGRM00DWZZHW7E",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45109.94918",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 5-8, 5-9",
    Ticket_Amt: "1000",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "2",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3745419725",
    Bkg_Id: "BGRM00WF33QF5N",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Iphone App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45111.48591",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "1",
    Ticketwise_Qty: "1",
    Seat_Info: "Row 1 to 18: 4-13",
    Ticket_Amt: "500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "1",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3745713701",
    Bkg_Id: "BGRM0Y10410E8D",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45111.70195",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 7-11, 7-12",
    Ticket_Amt: "1000",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "2",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3747659078",
    Bkg_Id: "BGRM003P0U5M6T",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45113.54096",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 7-21, 7-22",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3747678992",
    Bkg_Id: "BGRM003UU867N4",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Iphone App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45113.55446",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 19 to 20: 20-16, 20-17",
    Ticket_Amt: "600",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3747810734",
    Bkg_Id: "BGRM004GEBA8A2",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45113.64532",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "3",
    Ticketwise_Qty: "3",
    Seat_Info: "Row 1 to 18: 4-23, 4-24, 4-25",
    Ticket_Amt: "1500",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3748528432",
    Bkg_Id: "BGRM10KC910564",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45114.31557",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 4-6, 4-7",
    Ticket_Amt: "1000",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "2",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3748598163",
    Bkg_Id: "BGRM114YX12997",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45114.38507",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "1",
    Ticketwise_Qty: "1",
    Seat_Info: "Row 1 to 18: 5-10",
    Ticket_Amt: "500",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3748703389",
    Bkg_Id: "BGRM11QTR15G1H",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45114.4638",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "5",
    Ticketwise_Qty: "5",
    Seat_Info: "Row 1 to 18: 8-12, 8-13, 8-14, 8-15, 8-16",
    Ticket_Amt: "2500",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3748855413",
    Bkg_Id: "BGRM12DRJ1A4G9",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45114.56401",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 7-16, 7-17",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3749259374",
    Bkg_Id: "BGRM0148RCBC2R",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Iphone App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45114.81691",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 7-14, 7-15",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3749357173",
    Bkg_Id: "BGRM014M6DEBJZ",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45114.87052",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 19 to 20: 20-18, 20-19",
    Ticket_Amt: "600",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3749368151",
    Bkg_Id: "BGRM014RYNEPA1",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45114.87645",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "3",
    Ticketwise_Qty: "3",
    Seat_Info: "Row 1 to 18: 7-18, 7-19, 7-20",
    Ticket_Amt: "1500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "3",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3749532735",
    Bkg_Id: "BGRM015E9FKQ19",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45114.97287",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "1",
    Ticketwise_Qty: "1",
    Seat_Info: "Row 1 to 18: 5-22",
    Ticket_Amt: "500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "1",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3749583748",
    Bkg_Id: "BGRM00HTSXN8UE",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BookMyShow Website",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.01065",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "3",
    Ticketwise_Qty: "3",
    Seat_Info: "Row 1 to 18: 5-23, 5-24, 5-25",
    Ticket_Amt: "1500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "3",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3749647351",
    Bkg_Id: "BGRM00J7AWQ6Z1",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BookMyShow Website",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.07211",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "1",
    Ticketwise_Qty: "1",
    Seat_Info: "Row 1 to 18: 8-24",
    Ticket_Amt: "500",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3749883022",
    Bkg_Id: "BGRM00MA97YD3R",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.35354",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 8-18, 8-19",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750081777",
    Bkg_Id: "BGRM0N60K14F6U",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.46738",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 19 to 20: 20-20, 20-21",
    Ticket_Amt: "600",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750095225",
    Bkg_Id: "BGRM0N6WZ14WB3",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.47372",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 8-20, 8-21",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750155218",
    Bkg_Id: "BGRM0NEKS16PXW",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Iphone App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.50078",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "5",
    Ticketwise_Qty: "5",
    Seat_Info: "Row 1 to 18: 9-20, 9-21, 9-22, 9-23, 9-24",
    Ticket_Amt: "2500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "5",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750170755",
    Bkg_Id: "BGRM0NFHE1763D",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.5076",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "3",
    Ticketwise_Qty: "3",
    Seat_Info: "Row 1 to 18: 9-12, 9-13, 9-14",
    Ticket_Amt: "1500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "3",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750179151",
    Bkg_Id: "BGRM0NG3617E9S",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BookMyShow Website",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.5114",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 11-18, 11-19",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750193237",
    Bkg_Id: "BGRM0NGZE17W1Z",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Iphone App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.51769",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "3",
    Ticketwise_Qty: "3",
    Seat_Info: "Row 1 to 18: 10-12, 10-13, 10-14",
    Ticket_Amt: "1500",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750263147",
    Bkg_Id: "BGRM0NS8K1A0AN",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Iphone App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.54877",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 4-4, 4-5",
    Ticket_Amt: "1000",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "2",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750296052",
    Bkg_Id: "BGRM0NUAM1B0EY",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.5635",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 8-22, 8-23",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750315771",
    Bkg_Id: "BGRM000NWJXGSU",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.5724",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 5-6, 5-7",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750401839",
    Bkg_Id: "BGRM00P5Z934UF",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BMS Android App",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.61142",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "5",
    Ticketwise_Qty: "5",
    Seat_Info: "Row 1 to 18: 7-23, 7-24, 7-25, 7-26, 7-27",
    Ticket_Amt: "2500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "5",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750419981",
    Bkg_Id: "BGRM00P7543PJD",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.6199",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "2",
    Ticketwise_Qty: "2",
    Seat_Info: "Row 1 to 18: 10-24, 10-25",
    Ticket_Amt: "1000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750435977",
    Bkg_Id: "BGRM00PC444669",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.62739",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "4",
    Ticketwise_Qty: "4",
    Seat_Info: "Row 1 to 18: 9-15, 9-16, 9-17, 9-18",
    Ticket_Amt: "2000",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750521880",
    Bkg_Id: "BGRM00PP0B6T2R",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "Web App Mobile -V2",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.66997",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "5",
    Ticketwise_Qty: "5",
    Seat_Info: "Row 1 to 18: 10-16, 10-17, 10-18, 10-19, 10-20",
    Ticket_Amt: "2500",
    Item_Desc: "-",
    ItemWise_Amt: "-",
    ItemWise_Qty: "-",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
  {
    BackgroundColor: "#FFFFFF",
    Trans_Id: "3750767628",
    Bkg_Id: "BGRM00QKW3EA2C",
    Bkg_Commit: "Y",
    Pay_Status: "P",
    Appl_Name: "BookMyShow Website",
    Cinema_Name: "Bal Gandharva Rang Mandir: Pune",
    Screen_Name: "Bal Gandharva",
    Event_Name: "Mi, Swara Aani Te Dogha!",
    Trans_Date: "45115.79896",
    Show_Date: "45115.89583",
    Show_Date_Disp: "Jul  8 2023  9:30PM",
    Ticket_Qty: "3",
    Ticketwise_Qty: "3",
    Seat_Info: "Row 1 to 18: 10-9, 10-10, 10-11",
    Ticket_Amt: "1500",
    Item_Desc: "BookASmile",
    ItemWise_Amt: "1.00",
    ItemWise_Qty: "3",
    Inv_Qty: "0",
    Inv_Amt: "0",
    Additional_Desc: "-",
    Add_strAmt: "0.00",
    Add_Charges: "0",
    Cinema_DiscAmt: "0",
    Cinema_OfferCode: "",
    ETicket_Status: "-",
    SocialDistancing_count: "",
  },
];
